version: "3.1"
services:
    scheduler:
        volumes:
        - /Users/drewwhite/.creds/wdrew2-sa.json:/usr/local/airflow/gcloud/application_default_credentials.json:ro
        - /Users/drewwhite/Desktop/Epicodus/team-week3/drew-work/airflow/data/cities.json:/usr/local/airflow/data/cities.json
    webserver:
        volumes:
        - /Users/drewwhite/.creds/wdrew2-sa.json:/usr/local/airflow/gcloud/application_default_credentials.json:ro
        - /Users/drewwhite/Desktop/Epicodus/team-week3/drew-work/airflow/data/cities.json:/usr/local/airflow/data/cities.json
    triggerer:
        volumes:
        - /Users/drewwhite/.creds/wdrew2-sa.json:/usr/local/airflow/gcloud/application_default_credentials.json:ro
        - /Users/drewwhite/Desktop/Epicodus/team-week3/drew-work/airflow/data/cities.json:/usr/local/airflow/data/cities.json